### PR TITLE
Updated report button

### PR DESCRIPTION
**Pull request by huytran172**
Redesigned registration forms
Add report button. Can you please check if the path is correct? It returns HTTP 200 and an empty object.

### CODE REVIEW

**Review by marshall62 — CHANGES_REQUESTED** [review]
It looks like this pom.xml is old.   The newest one avoids bringing in unecessary libs.

**Review by marshall62 — CHANGES_REQUESTED** [review]
It looks like some of these files are older than the latest.  Please do not include project files such as these.   Your pom.xml also has a lot of outdated XML that has been removed from the latest.

**Review by marshall62 — APPROVED** [review]

**Review by marshall62 — CHANGES_REQUESTED** [review]
The ReportError event needs additional parameters and the dialog needs a checkbox (off by default) to say if the problem is broken or not.    If user checks, client should send server a NextProblem event after the ReportError event has results returned.

**Review by marshall62 — CHANGES_REQUESTED** [review]
remove main.iml

**Review by marshall62 — CHANGES_REQUESTED** [review]
remove

**Review by marshall62 — CHANGES_REQUESTED** [review]
remove main.iml

**Review by marshall62 — APPROVED** [review]

**Review by marshall62 — CHANGES_REQUESTED** [review]
old pom.xml.   I don't see the sass dependency

**Review by marshall62 — CHANGES_REQUESTED** [review]
eliminate the woserver.iml

**Comment by huytran172** [comment]
Hi David, all those file you mentioned are not changed in this pull request. You can see in the last two commits, I reset the config files to the master version and did not touch those files. There are 28 files changed in this PR, they are all JSP and SASS files. You can see the list in this screenshot, go to the PR -> Jump to dropdown

screen shot 2018-02-11 at 3 07 03 pm

**Pull request merged**
